% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name fd_in_parts
%  @associatedFile /MATLAB Drive/thesis/finite difference/fd_in_parts.m
%  @mostRecentlyActioned true
%  @uniqueId DA453592

fd_in_parts

%% @name fdsymmetric
%  @associatedFile /MATLAB Drive/thesis/finite difference/fdsymmetric.m
%  @mostRecentlyActioned true
%  @uniqueId E5B2BE48

fdsymmetric

%% @name sim_func
%  @associatedFile /MATLAB Drive/thesis/finite difference/sim_func.m
%  @mostRecentlyActioned true
%  @uniqueId B70FAF95

sim_func

%% @name imex
%  @associatedFile /MATLAB Drive/thesis/imex/imex.m
%  @mostRecentlyActioned true
%  @uniqueId 02D9D5B4

imex

%% @name imex2
%  @associatedFile /MATLAB Drive/thesis/imex/imex2.m
%  @mostRecentlyActioned true
%  @uniqueId D2E56DDA

imex2

%% @name multiple_alpha
%  @associatedFile /MATLAB Drive/graphs/multiple_alpha.m
%  @mostRecentlyActioned true
%  @uniqueId 0FAF4285

multiple_alpha

%% @name fd2d
%  @associatedFile /MATLAB Drive/thesis/finite difference/fd2d.m
%  @mostRecentlyActioned true
%  @uniqueId 35AF53D7

fd2d

%% @name matgen
%  @associatedFile /MATLAB Drive/final/FD/matgen.m
%  @mostRecentlyActioned true
%  @uniqueId 52D50B86

matgen

